### ISSUE TITLE
Authentication as User

### ISSUE THREAD

**Issue by j12y** [ikedam/authorize-project#1]
I was wondering if you could point me in the right direction.

I installed this plugin so that if I trigger the job it would run as me.
 - Enabled 'Run as User who Triggered Build' under Configure Global Security
 - Enabled 'Configure Build Authorization' and 'Run as User who Triggered Build' in my project
 - Added Build step to run shell command `whoami`

The console output says:

> Started by user *my name*

> Running as *my name*

> Building in workspace *my path*

> \+ whoami 

> jenkins

I would have expected my username there, not jenkins.  Does the jenkins system acct need permission to sudo to users?

**Comment by ikedam** [comment]
https://wiki.jenkins-ci.org/display/JENKINS/Authorize+Project+plugin?focusedCommentId=74875042#comment-74875042

**Comment by j12y** [comment]
Ah, sorry -- I missed that in the comments.  Thanks for pointing it out.
